Dockerfile
install_ruby.sh

Currently, `bundler --version` on ruby:2.7.0-preview-1-bionic doesn't work:
```
$ docker run rubylang/ruby:2.7.0-preview1-bionic bundler --version
/usr/local/lib/ruby/2.7.0/rubygems.rb:281:in `find_spec_for_exe': Could not find 'bundler' (1.17.3) required by `$BUNDLER_VERSION`. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:1.17.3`
from /usr/local/lib/ruby/2.7.0/rubygems.rb:300:in `activate_bin_path'
from /usr/local/bin/bundler:23:in `<main>'
```
Because `BUNDLER_VERSION` restricts bundler version for bundler 2:
https://github.com/docker-library/ruby/issues/246
On docker-library, it was already solved by removing BUNDLER_VERSION and installing newer rubygems: …

Remove BUNDLER_VERSION env variable

---

README.md

Neither GitHub repository name nor DockerHub repository name includes "RubyData" now.

The repository seems to be transferred to ruby

---

Dockerfile
install_ruby.sh

Reverts ruby/ruby-docker-images#5 because the circleci workflow was failed.
https://circleci.com/gh/ruby/ruby-docker-images/316?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification

Revert "Remove BUNDLER_VERSION env variable"

---

Dockerfile
install_ruby.sh

This pull request removes  BUNDLER_VERSION environment variable
* No need to install bundler separately because `gem update --system 3.0.3` installs bundler 1.17.3
Refer one of the minor enhancements of RubyGems 3.0.2:
https://github.com/rubygems/rubygems/blob/919239f65daf74bce53935e191e0e57aabcb80a7/History.txt#L74
RubyGems 3.0.3 only has security fixes. No Bundler version bump found.
* Exporting `BUNDLER_VERSION=1.17.3` causes the error at Ruby 2.7.0 master
which installs `Bundler version 2.1.0.pre.1`
```
/usr/local/lib/ruby/2.7.0/rubygems.rb:281:in `find_spec_for_exe': Could not find 'bundler' (1.17.3) required by `$BUNDLER_VERSION`. (Gem::GemNotFoundException)
```
* Add a rough smoke test to show which RubyGem and Bundler versions installed
Refer #5
Co-authored-by: Fumiaki MATSUSHIMA …

Remove BUNDLER_VERSION environment variable

---

.circleci/config.yml

To prevent a mistake like https://github.com/ruby/ruby-docker-images/pull/6, I'd like to run docker build on every PR.

Run docker build on PR

---

.circleci/config.yml

I changed circleci config in #7 and I forgot to add this flag to build_trunk 🙇 
As a result, trunk isn't pushed since my PR got merged 🙇 🙇 🙇 
https://hub.docker.com/r/rubylang/ruby/tags

Enable push for nightly build

---

.circleci/config.yml
README.md
Rakefile
install_ruby.sh

After 4 months from now, trunk branch will be removed. Thus we should not rely on the branch at least. I also prefer renaming tag names for consistency.

Fix s/trunk/master/

---

Dockerfile

When we use the `actions/checkout@v2` in GitHub Actions, It needs to `>= git 2.18` for full of features. 
Ubuntu bionic provide git-2.17.1. It's nice to upgrade the git version for users.
How about this?

Added the git repo provided by PPA. 

---

install_ruby.sh

Hi Team!
Since the tmp file remains after downloading Ruby, the old version of Gemfile.lock remains, and some Docker image scanners have determined that it is vulnerable, so delete unnecessary files. ..
Rubyのダウンロード後にtmpファイルが残っていることで、tmp/www/Gemfile.lockの古いバージョンが残っており、一部のDockerイメージのスキャナーで脆弱性があると判定されているので、不要なファイルは削除します。

delete /tmp/www after clone

---

Dockerfile
Dockerfile-arm64

Hi team!
thanks for your contribution to Ruby!
This PR is to adjust to Docker build Best Practice. 
https://docs.docker.com/develop/develop-images/dockerfile_best-practices/
Acording to *Best practices for writing Dockerfiles*, apt list is cached to Docker image when `rm -r /var/lib/apt/lists/*`  execute that defferent `apt install or apt update` RUN command.
> In addition, when you clean up the apt cache by removing /var/lib/apt/lists it reduces the image size, since the apt cache is not stored in a layer. Since the RUN statement starts with apt-get update, the package cache is always refreshed prior to apt-get install.
I think it's a bit verbose, but I tried to delete the cache after the every apt command.
Thanks.

Delete apt cache every execute apt command

---

.github/workflows/build.yml

Fix: https://github.com/ruby/ruby-docker-images/runs/2136097570?check_suite_focus=true
Hi Team!
[3 months ago, `ubuntu-latest` was `ubuntu-18.04`](https://github.com/ruby/ruby-docker-images/runs/1607733686?check_suite_focus=true#step:1:4), so the docker command was older and could push all images without options.
[Now it's `ubuntu-20.04`](https://github.com/ruby/ruby-docker-images/runs/2136097570?check_suite_focus=true#step:1:4), so you need the `--all-tags` option to push all tags.

Add --all-tags option to push all images

---

Rakefile

This pull request allows Ruby 3.1 which bundles Psych 4 to build Docker images.
* Without this commit
```ruby
$ ruby -v
ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [x86_64-linux]
$ gem info psych
*** LOCAL GEMS ***
psych (4.0.3)
Authors: Aaron Patterson, SHIBATA Hiroshi, Charles Oliver Nutter
Homepage: https://github.com/ruby/psych
License: MIT
Installed at (default): /home/yahonda/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0
Psych is a YAML parser and emitter
$ rake -v docker:build ruby_version=3.1.0
rake aborted!
ArgumentError: wrong number of arguments (given 2, expected 1)
/home/yahonda/src/github.com/ruby/ruby-docker-images/Rakefile:25:in `ruby_versions'
/home/yahonda/src/github.com/ruby/ruby-docker-images/Rakefile:46:in `ruby_version_exist?' …
```

Support Psych 4.0 which is bundled with Ruby 3.1

---

Dockerfile-arm64

Some images for arm64 are built with wrong base image like bellow.
```
$ docker run --rm rubylang/ruby:3.1.2-focal-arm64 cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.6 LTS"
```
So, I fixed `Dockerfile-arm64` file enable to change the base image tag same as `Dockerfile`.

Fix wrong base image for some arm64 images

---

Dockerfile
Dockerfile-arm64

According to [Best practices for writing Dockerfiles](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/), change `ADD` instruction to `COPY`.
Some container image linter like [Dockle](https://github.com/goodwithtech/dockle) does not allow to use `COPY`.

Use COPY instead of ADD in Dockerfile

---

Dockerfile-arm64

Resolve differences between `Dockerfile` and `Dockerfile-arm64`.
Newer git brings better experience for developers and some gems like sassc need g++ to build. And I think that the fewer differences between architectures is better.

Resolve differences between Dockerfile and Dockerfile-arm64

---

Dockerfile
install_ruby.sh
ruby_build_deps.txt

This PR installs Rust in the Dockerfile and enables yjit in the images. The change here is useful for using and testing yjit without being required to manually configure Ruby. One usecase is to add a build to rails/rails to test our code against yjit.
I tested this locally and was able to build the docker image and verified it built correctly and I could use yjit by running the following command:
```
$ RUBY_YJIT_ENABLE=1 ruby -e 'p RubyVM::YJIT.enabled?'
=> true
```

Install rust and enable yjit

---

Rakefile

It seems strange that the date in the Docker tag name and the one in RUBY_DESCRIPTION are inconsistent:
```
$ docker run --rm rubylang/ruby:master-nightly-20221125-focal ruby -v
ruby 3.2.0dev (2022-11-24T15:30:28Z master d2fa67de81) [x86_64-linux]
```
This is caused by the fact that ruby/ruby's revision.h uses UTC https://github.com/ruby/ruby/blob/ac4d00df824215d4b85d36cef75c76543fead33e/tool/lib/vcs.rb#L266 and ruby-docker-images uses JST. Using the same timezone between them seems more useful.

Use the same timezone as revision.h

---

Dockerfile

Fixed https://github.com/ruby/ruby-docker-images/issues/46

Use RUBY_SO_SUFFIX_MM instead of RUBY_VERSION_MM

---

README_dockerhub.md

But there is not `rubylang/ruby:3.2.3-dev-focal`, and `docker run --rm -it rubylang/ruby:3.2-dev-focal ruby -v` outputs `ruby 3.2.2 (2023-03-30 revision e51014f9c0) [aarch64-linux]`.

rubylang/ruby:3.2-focal is rubylang/ruby:3.2.3-focal

---

.github/actions/build_image/action.yml
.github/actions/push_image/action.yml
.github/actions/push_image_by_tag/action.yml
.github/workflows/build_multiarch.yml
.github/workflows/nightly.yml

Pipeline migrated from [CircleCI](https://app.circleci.com/pipelines/github/ruby/ruby-docker-images) :tada:
Perform the following steps to complete the migration:

Convert ruby/ruby-docker-images to GitHub Actions

---

.github/actions/build_image/action.yml
.github/workflows/build_multiarch.yml
Rakefile

`marcos-arm-oss` runner didn't support `docker` command yet. We need to use `buildx` for arm64 build.

Use buildx when specified arm64

---

Dockerfile

`sqlite3-ruby` needs `pkg-config`
```
Building native extensions. This could take a while...
ERROR:  Error installing sqlite3:
ERROR: Failed to build gem native extension.
current directory: /usr/local/lib/ruby/gems/3.4.0+0/gems/sqlite3-1.7.2/ext/sqlite3
/usr/local/bin/ruby extconf.rb
Building sqlite3-ruby using packaged sqlite3.
Extracting sqlite-autoconf-3450100.tar.gz into tmp/x86_64-linux-gnu/ports/sqlite3/3.45.1... OK
Running 'configure' for sqlite3 3.45.1... OK
Running 'compile' for sqlite3 3.45.1... OK
Running 'install' for sqlite3 3.45.1... OK
Activating sqlite3 3.45.1 (from /usr/local/lib/ruby/gems/3.4.0+0/gems/sqlite3-1.7.2/ports/x86_64-linux-gnu/sqlite3/3.45.1)...
checking for pkg-config for /usr/local/lib/ruby/gems/3.4.0+0/gems/sqlite3-1.7.2/ports/x86_64-linux-gnu/sqlite3/3.45. …
```

Added pkg-config for sqlite3-ruby

---

Dockerfile

Fixes https://github.com/ruby/ruby-docker-images/issues/78

Install Ruby 3.2.3 to base-image

---

Dockerfile
install_ruby.sh

I install Ruby 3.2 as BASERUBY at https://github.com/ruby/ruby-docker-images/pull/80
BASERUBY uses same prefix for final image. So, we have some of garbage from BASERUBY at https://github.com/ruby/ruby-docker-images/issues/78#issuecomment-1958582794
I change to use different directory for BASERUBY.

Use /root directory to install BASERUBY

---

.github/workflows/build.yml
.github/workflows/build_multiarch.yml
.github/workflows/nightly.yml

If some job is failed, we can't build and push all images. 
https://github.com/ruby/ruby-docker-images/actions/runs/9001512315 
We should try to build other images.

Don't stop all in-progress jobs if any matrix job fails.

---

Rakefile

We sometimes faced https://github.com/ruby/docker-images/actions/runs/10958936683/job/30430235649#step:9:68. It caused commit mismatch between build and push.
I enabled cache file for that differences.

Fix flaky image build

---

Dockerfile
install_ruby.sh

from https://github.com/ruby/docker-images/actions/runs/11097384195/job/30828525468#step:8:5499
I'm not sure why our image couldn't search .so files from `/usr/local/lib` as LD_LIBRARY_PATH. I manually added it.

Added LD_LIBRARY_PATH to published images

---

Dockerfile
install_ruby.sh

https://github.com/ruby/ruby/commit/79a8750ade3e332c1ab78aa9cbc6ca7fd823dec2 is fixed root cause of this.

Revert "Added LD_LIBRARY_PATH to published images"

---

install_ruby.sh

Fix https://github.com/ruby/docker-images/actions/runs/11591149300/job/32270268536#step:5:3268
We can't look releases.yml at that time. we should refer tar file directly.

Don't use releases.yml when release time.

---

Rakefile

I think here is root cause of following exception:
```
ArgumentError: Invalid commit_hash: "{\"message\""
/home/runner/work/docker-images/docker-images/Rakefile:145:in `get_ruby_version_at_commit'
/home/runner/work/docker-images/docker-images/Rakefile:202:in `block (2 levels) in <top (required)>'
```

Check exit status of curl

---

.github/workflows/build_multiarch.yml
.github/workflows/test.yml

https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/

Use native arm runner

---

Dockerfile

We will remove irb and ri manpages at Ruby 3.5. Dockerfile should support it.

Use more regex

---

.github/workflows/test.yml

We can pull base images from ghcr.io now.

Don't need docker/login-action now

---

Dockerfile
install_ruby.sh

This PR enables ZJIT support.
I want to use the Docker images for benchmarking ZJIT. At the moment, Ruby's `configure` enables only YJIT by default, so we need to explicitly specify `--enable-zjit` for now. Note that ZJIT requires newer Rust and building both YJIT and ZJIT requires cargo, so it changed the Rust installation method to rustup.

Enable ZJIT

---

.github/workflows/build.yml
.github/workflows/test.yml
Rakefile

This PR adds tags like `master-YYYYMMDD`. 
We used to have nightly tags like `master-nightly-YYYYMMDD-focal`, but https://github.com/ruby/docker-images/pull/115 removed every `nightly: true` job, so such tags are no longer pushed. The first commit of this PR removes the code that was used by `nightly: true`, which is `each_nightly_tag`. It also removes the `rake docker:push` target, which is not used either.
To make sure we push the `YYYYMMDD`-based tags, this PR adds the tag in `make_tags`. To ensure the consistency between `RUBY_RELEASE_DATE` and the date in the tag name, it fetches the commit date using GitHub API.

Push commit date tags
